name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Code analysis and tests

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build solution
        run: dotnet build Geodatenbezug.sln -c Release /warnaserror

      - name: Run tests
        run: dotnet test Geodatenbezug.sln -c Release --no-build --verbosity normal
