name: Pre-release

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
    PYTHON_VERSION: "3.11"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}

            - name: Create and start virtual environment
              run: |
                  python -m venv venv
                  source venv/bin/activate

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: python-app
                  path: |
                      release.zip
                      !venv/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "production"
            url: ${{ steps.deploy-to-function.outputs.webapp-url }}
        permissions:
            id-token: write

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: python-app

            - name: Unzip artifact for deployment
              run: unzip release.zip

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4DEC88A8D4E9449FB95137483FD586C1 }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D31EB2CA5C2A41E493832FAA4D289313 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_53F79E670D784A1C884DFE31CFF3B8E4 }}

            - name: "Deploy to Azure Functions"
              uses: Azure/functions-action@v1
              id: deploy-to-function
              with:
                  app-name: "geodatenbezug"
                  slot-name: "production"
                  package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
                  scm-do-build-during-deployment: true
                  enable-oryx-build: true
