name: Release

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: "Tag name"
        required: true

env:
  REGISTRY: ghcr.io
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  AZURE_FUNCTIONAPP_NAME: "geodatenbezug"
  AZURE_FUNCTIONAPP_SLOT: "production"
  DOTNET_VERSION: "8.0.x"

jobs:
  build-and-deploy-prod:
    runs-on: windows-latest
    name: Build and deploy to production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build solution
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FC79ACD3493F4D6CB09C619860F15688 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DC41E352EF2D471992D5623CB1879E27 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_28EB1A5320E2429ABBCF9298EB712AD3 }}

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: "${{ env.AZURE_FUNCTIONAPP_NAME }}"
          slot-name: "${{ env.AZURE_FUNCTIONAPP_SLOT }}"
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"

  patch-changelog:
    needs: build-and-deploy-prod
    runs-on: ubuntu-latest
    name: Patch CHANGELOG.md and update GitHub release notes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo GIT_BRANCH_NAME=mark-version-${TAG_NAME#v}-as-released >> $GITHUB_ENV
          echo GIT_COMMIT_MESSAGE=Mark version ${TAG_NAME#v} as released >> $GITHUB_ENV
          echo RELEASE_ID=$(gh api -H "Accept: application/vnd.github+json" /repos/${GITHUB_REPOSITORY}/releases/tags/${TAG_NAME} | jq '.id') >> $GITHUB_ENV

      - name: Get changelog for this specific release and update release notes
        run: |
          gh api \
            --method PATCH \
            --header "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID} \
            -f body="$(./get-changelog.sh)"

      - name: Checkout new branch and patch changelog
        run: |
          git checkout -b $GIT_BRANCH_NAME
          sed -i "/^\#\# \[Unreleased\]$/a \\\n\#\# $TAG_NAME - $(date '+%Y-%m-%d')" CHANGELOG.md

      - name: Commit, push and create pull request
        run: |
          git config --global user.email "office@geowerkstatt.ch"
          git config --global user.name "GeoWerkstatt-Build"
          git commit -am "$GIT_COMMIT_MESSAGE"
          git push --set-upstream origin $GIT_BRANCH_NAME
          gh pr create --title "$GIT_COMMIT_MESSAGE" --body ""
